import React, { useState, useEffect } from 'react'
import Head from 'next/head';
import { Transition } from "@headlessui/react"
import { HiSun, HiMoon } from 'react-icons/hi';
import { useTheme } from 'next-themes';
import Image from 'next/image';

export default function Layout({ title, children }) {
    const { systemTheme, theme, setTheme } = useTheme();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    const renderThemeChanger = () => {
        if(!mounted) return <div>Not available</div>;

        const currentTheme = theme === 'system' ? systemTheme : theme;
        if(currentTheme === 'dark') {
            return  (
                <HiSun 
                   className='w-7 h-7' 
                   role="button" 
                   onClick={() => setTheme('light')} 
                />
            )
        }
        else {
            return  (
                <HiMoon 
                   className='w-7 h-7' 
                   role="button" 
                   onClick={() => setTheme('dark')} 
                />
            )
        }
    }

    const [isOpen, setIsOpen] = useState(false);
    return (
        <>
            <Head>
                <title>{title ? title + ' - Frontend Dev...' : 'Frontend Dev...'}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex min-h-screen flex-col justify-between">
                <header>
                    <nav className='border-b border-gray-100 dark:border-gray-700 shadow-sm bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100'>
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex items-center justify-between h-16">
                        <div className="flex items-center">
                        <div className="flex-shrink-0">
                            <div  className="h-8 w-8">
                                <Image
                                width={65}
                                height={65}
                                src="https://www.svgrepo.com/show/295398/code.svg"
                                alt="Workflow"
                                />
                            </div>
                        </div>
                        <div className="hidden md:block">
                            <div className="ml-10  flex items-center gap-12 justify-between space-x-4">
                            <a
                                href="#"
                                className="text-indigo-600 dark:text-gray-300 hover:text-indigo-500 px-3 py-2 rounded-md text-xl font-medium"
                            >
                                ABDULLAH
                            </a>

                            <a
                                href="#about"
                                className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                            >
                                About
                            </a>

                            <a
                                href="#skills"
                                className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                            >
                               Skills
                            </a>

                            <a
                                href="#projects"
                                className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                            >
                                Projects
                            </a>

                            <a
                                href="#contact"
                                className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                            >
                                Contact
                            </a>

                            <a
                                href="https://dakta.hashnode.dev/"
                                
                                className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                            >
                                Blog
                            </a>

                            <a
                                href="#"
                                className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                            >
                                  {renderThemeChanger()} 
                            </a>
                            </div>
                        </div>
                        </div>
                        <div className="-mr-2 flex md:hidden">
                        <button
                            onClick={() => setIsOpen(!isOpen)}
                            type="button"
                            className="bg-gray-900 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                            aria-controls="mobile-menu"
                            aria-expanded="false"
                        >
                            <span className="sr-only">Open main menu</span>
                            {!isOpen ? (
                            <svg
                                className="block h-6 w-6"
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                                aria-hidden="true"
                            >
                                <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth="2"
                                d="M4 6h16M4 12h16M4 18h16"
                                />
                            </svg>
                            ) : (
                            <svg
                                className="block h-6 w-6"
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                                aria-hidden="true"
                            >
                                <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth="2"
                                d="M6 18L18 6M6 6l12 12"
                                />
                            </svg>
                            )}
                        </button>
                        </div>
                    </div>
                    </div>

                    <Transition
                    show={isOpen}
                    enter="transition ease-out duration-100 transform"
                    enterFrom="opacity-0 scale-95"
                    enterTo="opacity-100 scale-100"
                    leave="transition ease-in duration-75 transform"
                    leaveFrom="opacity-100 scale-100"
                    leaveTo="opacity-0 scale-95"
                    >
                    {(ref) => (
                        <div className="md:hidden" id="mobile-menu">
                        <div ref={ref} className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                            <a
                            href="#"
                            className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                            >
                            About
                            </a>

                            <a
                            href="#"
                            className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                            >
                            Skills
                            </a>

                            <a
                            href="#"
                            className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                            >
                            Projects
                            </a>

                            <a
                            href="#"
                            className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                            >
                            Contact
                            </a>

                            <a
                            href="#"
                            className="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
                            >
                            Blog
                            </a>

                            <a
                            href="#"
                            className="text-gray-300  block px-3 py-2 rounded-md text-base font-medium"
                            >
                            {renderThemeChanger()}
                            </a>
                        </div>
                        </div>
                    )}
                    </Transition>
                </nav>
                </header>
                <main>
                    {children}
                </main>
                <footer>
                    footer
                </footer>
            </div>
        </>
    )
}